[package]
name = "near-units-core"
version = "0.1.0"
authors = ["Near Inc <team@near.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
num-format = "0.4.0"